import React from 'react'

function Blog() {
    return (
        <section className='py-5'>
            <div className='container'>
                <h1 className='text-center fs-4 mb-5'>Bài viết</h1>

                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Laborum labore fugiat voluptate, dicta veritatis maiores illo provident excepturi quisquam ut temporibus perferendis non eos eligendi vel magni beatae earum exercitationem? Eos pariatur dolorum distinctio quaerat quibusdam voluptas commodi, alias iste porro in illum nam odio esse veniam, suscipit quidem est rerum quos ab. Officia, ut harum labore minus iusto, iure excepturi fugiat soluta obcaecati in natus quidem possimus blanditiis delectus animi ratione quasi hic culpa, voluptas velit error mollitia unde dolorum totam. Illo, maiores recusandae dicta illum architecto consequuntur autem reprehenderit commodi dolores ipsa, cumque optio voluptates ducimus libero est sunt dignissimos soluta? Voluptatum tempore quo quae adipisci commodi error delectus totam sunt, fuga reiciendis iusto, atque enim excepturi eum quidem harum itaque amet nostrum magnam. Sunt cum facere unde ad qui repellendus obcaecati eius delectus possimus ipsum consequatur voluptatem distinctio tempore voluptates, suscipit voluptas sit facilis, alias, sequi dolore quas deleniti at? Voluptatem saepe voluptate asperiores ut quo culpa modi cum, illo, rem nesciunt fugit cupiditate magni, iste quod totam quis animi dolorem! Quasi nostrum minima, animi enim ratione hic illo culpa perferendis, sapiente nulla molestiae ad vel vitae optio saepe? Id suscipit tenetur, tempore iure fugit nihil placeat?</p>

                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Laborum labore fugiat voluptate, dicta veritatis maiores illo provident excepturi quisquam ut temporibus perferendis non eos eligendi vel magni beatae earum exercitationem? Eos pariatur dolorum distinctio quaerat quibusdam voluptas commodi, alias iste porro in illum nam odio esse veniam, suscipit quidem est rerum quos ab. Officia, ut harum labore minus iusto, iure excepturi fugiat soluta obcaecati in natus quidem possimus blanditiis delectus animi ratione quasi hic culpa, voluptas velit error mollitia unde dolorum totam. Illo, maiores recusandae dicta illum architecto consequuntur autem reprehenderit commodi dolores ipsa, cumque optio voluptates ducimus libero est sunt dignissimos soluta? Voluptatum tempore quo quae adipisci commodi error delectus totam sunt, fuga reiciendis iusto, atque enim excepturi eum quidem harum itaque amet nostrum magnam. Sunt cum facere unde ad qui repellendus obcaecati eius delectus possimus ipsum consequatur voluptatem distinctio tempore voluptates, suscipit voluptas sit facilis, alias, sequi dolore quas deleniti at? Voluptatem saepe voluptate asperiores ut quo culpa modi cum, illo, rem nesciunt fugit cupiditate magni, iste quod totam quis animi dolorem! Quasi nostrum minima, animi enim ratione hic illo culpa perferendis, sapiente nulla molestiae ad vel vitae optio saepe? Id suscipit tenetur, tempore iure fugit nihil placeat?</p>

                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Laborum labore fugiat voluptate, dicta veritatis maiores illo provident excepturi quisquam ut temporibus perferendis non eos eligendi vel magni beatae earum exercitationem? Eos pariatur dolorum distinctio quaerat quibusdam voluptas commodi, alias iste porro in illum nam odio esse veniam, suscipit quidem est rerum quos ab. Officia, ut harum labore minus iusto, iure excepturi fugiat soluta obcaecati in natus quidem possimus blanditiis delectus animi ratione quasi hic culpa, voluptas velit error mollitia unde dolorum totam. Illo, maiores recusandae dicta illum architecto consequuntur autem reprehenderit commodi dolores ipsa, cumque optio voluptates ducimus libero est sunt dignissimos soluta? Voluptatum tempore quo quae adipisci commodi error delectus totam sunt, fuga reiciendis iusto, atque enim excepturi eum quidem harum itaque amet nostrum magnam. Sunt cum facere unde ad qui repellendus obcaecati eius delectus possimus ipsum consequatur voluptatem distinctio tempore voluptates, suscipit voluptas sit facilis, alias, sequi dolore quas deleniti at? Voluptatem saepe voluptate asperiores ut quo culpa modi cum, illo, rem nesciunt fugit cupiditate magni, iste quod totam quis animi dolorem! Quasi nostrum minima, animi enim ratione hic illo culpa perferendis, sapiente nulla molestiae ad vel vitae optio saepe? Id suscipit tenetur, tempore iure fugit nihil placeat?</p>
            </div>
        </section>
    )
}

export default Blog